# -*- coding: utf-8 -*-
"""sparks_foundation_task1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N9P09-T9KGktDV6TEW-ElBFzUOlGKdk8

The Sparks Foundation Task-1
# Task-1: Prediction of the percentage of an student based on the no. of study hours using Supervised ML

Performed by: Sakshi Ingole

Batch : Feb,21
"""

# Importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset

from google.colab import files
uploaded = files.upload()
dataset = pd.read_csv('task1.csv')
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

# Printing the given Data Set
print(x)

print(y)

# Splitting the dataset into the Training set and Test set

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size =0.2, random_state = 0)

print(x_train)

print(x_test)

print(y_train)

print(y_test)

# Training the Simple Linear Regression model on the Training set

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)

# Predicting the Test set results

y_pred = regressor.predict(x_test)

# Visualising the Training set results

plt.scatter(x_train, y_train, color='red')
plt.plot(x_train,regressor.predict(x_train),color='blue')
plt.title('Scores VS Hours(Training Set)')
plt.xlabel('Number of Hours studied')
plt.ylabel('Scores')
plt.show()

# Visualising the Test set results

plt.scatter(x_test, y_test, color='red')
plt.plot(x_train,regressor.predict(x_train),color='blue')
plt.title('Scores VS Hours (Testing Set)')
plt.xlabel('Number of Hours studied')
plt.ylabel('Scores')
plt.show()

y_predict = regressor.predict([[9.25]])

print(y_predict)

# Evaluating the Model

from sklearn import metrics  
print('Mean Absolute Error:', 
      metrics.mean_absolute_error(y_test, y_pred))